# Fish completions for CoreX (cx) - Auto-generated Phase 3
complete -c cx -f
complete -c cx -s h -l help -d 'Show CoreX help message'
complete -c cx -s v -l version -d 'Show CoreX version'
complete -c cx -l list -d 'Output tab-delimited command list'
complete -c cx -l dry-run -d 'Preview commands without executing them'
complete -c cx -l bg -d 'Detach command into background daemon scope'
complete -c cx -l no-color -d 'Disable ANSI terminal styling'
complete -c cx -l config -r -F -d 'Custom TOML configuration path'
complete -c cx -s y -l yes -d 'Bypass confirmation prompts'
complete -c cx -n '__fish_use_subcommand' -a 'comfy-boot' -d 'Detect venv, check port 8188, apply CUDA alloc flags, launch ComfyUI & notify'
complete -c cx -n '__fish_use_subcommand' -a 'comfy-nuke' -d 'Force kill any zombie ComfyUI server and associated Python/Torch memory holders'
complete -c cx -n '__fish_use_subcommand' -a 'comfy-sync' -d 'Parallel git-pull across ComfyUI core and all cloned custom_nodes directories'
complete -c cx -n '__fish_use_subcommand' -a 'model-symlink' -d 'Interactive fzf picker to symlink any .safetensors file into target ComfyUI model folder'
complete -c cx -n '__fish_use_subcommand' -a 'ollama-up' -d 'Start the Ollama background inference daemon if stopped'
complete -c cx -n '__fish_use_subcommand' -a 'ollama-ps' -d 'Display currently loaded models in GPU memory with context memory footprint'
complete -c cx -n '__fish_use_subcommand' -a 'ollama-drop' -d 'Unload all active LLMs from VRAM immediately'
complete -c cx -n '__fish_use_subcommand' -a 'ollama-fzf' -d 'Interactive fzf selector to run or chat with any locally pulled model'
complete -c cx -n '__fish_use_subcommand' -a 'hf-download' -d 'Fast model puller from HuggingFace via aria2c multithreaded resume'
complete -c cx -n '__fish_use_subcommand' -a 'civit-grab' -d 'Download model/LoRA from Civitai API key/URL with SHA256 verification'
complete -c cx -n '__fish_use_subcommand' -a 'vram-watch' -d 'Loop nvidia-smi showing per-process memory, power draw, and temperature at 1000ms'
complete -c cx -n '__fish_use_subcommand' -a 'cuda-purge' -d 'Scan specifically for orphaned Python processes holding /dev/nvidia* file handles and terminate them'
complete -c cx -n '__fish_use_subcommand' -a 'stream-yt' -d 'Interactive YouTube fuzzy search via yt-dlp metadata streaming directly into mpv --no-video'
complete -c cx -n '__fish_use_subcommand' -a 'stream-video' -d 'Search YouTube and stream hardware-accelerated 1440p/4K video directly into borderless mpv'
complete -c cx -n '__fish_use_subcommand' -a 'stream-radio' -d 'Background endless ambient/lo-fi/synthwave stream player with minimal CPU footprint'
complete -c cx -n '__fish_use_subcommand' -a 'rip-flac' -d 'Batch-convert video or audio files in current directory to uncompressed 24-bit FLAC'
complete -c cx -n '__fish_use_subcommand' -a 'rip-opus' -d 'Fast high-efficiency audio compression to Opus at 160kbps'
complete -c cx -n '__fish_use_subcommand' -a 'trim-video' -d 'Interactive lossless video cutter via ffmpeg stream copy (start, end timestamps without re-encoding)'
complete -c cx -n '__fish_use_subcommand' -a 'make-gif' -d 'High-fidelity palettegen GIF converter from any video segment'
complete -c cx -n '__fish_use_subcommand' -a 'demucs-stems' -d 'Demix any audio track in cwd into 4 isolated stems (vocals, drums, bass, other) via local Demucs CLI'
complete -c cx -n '__fish_use_subcommand' -a 'pw-restart' -d 'One-key reboot of PipeWire, WirePlumber, and pipewire-pulse daemons'
complete -c cx -n '__fish_use_subcommand' -a 'pw-devices' -d 'Interactive fzf picker to switch default audio output sink on the fly'
complete -c cx -n '__fish_use_subcommand' -a 'pw-volume' -d 'Interactive CLI volume fader for master audio channel'
complete -c cx -n '__fish_use_subcommand' -a 'tag-editor' -d 'Fast CLI audio metadata editor/inspector via ffprobe'
complete -c cx -n '__fish_use_subcommand' -a 'cover-extract' -d 'Extract embedded album art from FLAC/MP3 files into cover.jpg'
complete -c cx -n '__fish_use_subcommand' -a 'gpu-clock' -d 'Toggle GPU power limit or persistence mode for maximum sustained clocks'
complete -c cx -n '__fish_use_subcommand' -a 'cpu-gov' -d 'Interactive picker for CPU governors (performance, powersave, schedutil)'
complete -c cx -n '__fish_use_subcommand' -a 'cpu-turboboost' -d 'Toggle Intel/AMD Turbo Boost state on/off'
complete -c cx -n '__fish_use_subcommand' -a 'mon-res' -d 'Toggle primary monitor refresh rates (e.g., 360Hz / 240Hz / 144Hz) via compositor'
complete -c cx -n '__fish_use_subcommand' -a 'mon-dual' -d 'Set dual-monitor arrangement preset'
complete -c cx -n '__fish_use_subcommand' -a 'mon-single' -d 'Disable secondary monitor and enforce max refresh rate on primary display'
complete -c cx -n '__fish_use_subcommand' -a 'sens-watch' -d 'Clean ANSI visual dashboard for NVMe, GPU hotspot, and CPU per-core temperatures'
complete -c cx -n '__fish_use_subcommand' -a 'game-mode' -d 'Kill non-essential background daemons, switch CPU to performance, and enable GameMode'
complete -c cx -n '__fish_use_subcommand' -a 'snap-now' -d 'Prompt for a quick snapshot comment and trigger an instant Snapper/BTRFS root snapshot'
complete -c cx -n '__fish_use_subcommand' -a 'snap-fzf' -d 'Interactive browser of past snapshots with rollback commands and file diff preview'
complete -c cx -n '__fish_use_subcommand' -a 'snap-clean' -d 'Prune old or orphaned system snapshots'
complete -c cx -n '__fish_use_subcommand' -a 'fkill' -d 'Interactive multi-select process terminator with live CPU/RAM previews'
complete -c cx -n '__fish_use_subcommand' -a 'disk-space' -d 'Interactive visual disk usage explorer via ncdu or dust'
complete -c cx -n '__fish_use_subcommand' -a 'pkg-orphans' -d 'Scan and remove unneeded package dependencies and clean package cache'
complete -c cx -n '__fish_use_subcommand' -a 'service-fail' -d 'List all failed systemd system and user services (systemctl --failed)'
complete -c cx -n '__fish_use_subcommand' -a 'journal-vacuum' -d 'Trim systemd logs to under 200MB'
complete -c cx -n '__fish_use_subcommand' -a 'boot-analyze' -d 'Profile kernel and userspace boot duration via systemd-analyze blame'
complete -c cx -n '__fish_use_subcommand' -a 'my-ip' -d 'Detailed ANSI card showing Public IP, Local IP, Gateway, ISP, and Geo-coordinates'
complete -c cx -n '__fish_use_subcommand' -a 'vpn-up' -d 'Interactive fzf selector for WireGuard/OpenVPN/Proton configuration profiles'
complete -c cx -n '__fish_use_subcommand' -a 'vpn-down' -d 'Clean disconnect and DNS leak prevention restore'
complete -c cx -n '__fish_use_subcommand' -a 'port-audit' -d 'Interactive open-port inspector (ss -tulpn) showing PID/service and one-key process kill'
complete -c cx -n '__fish_use_subcommand' -a 'speed-check' -d 'Fast network speed and latency test'
complete -c cx -n '__fish_use_subcommand' -a 'lan-scan' -d 'ARP scan local subnet to list active devices, IP addresses, and MAC vendors'
complete -c cx -n '__fish_use_subcommand' -a 'ssh-fzf' -d 'Interactive fuzzy selector pulling hosts from ~/.ssh/config for one-key remote connection'
complete -c cx -n '__fish_use_subcommand' -a 'serve-dir' -d 'Spin up an instant ad-hoc Python HTTP file server in cwd and show a scannable QR code'
complete -c cx -n '__fish_use_subcommand' -a 'dns-flush' -d 'Flush local systemd-resolved DNS cache'
complete -c cx -n '__fish_use_subcommand' -a 'git-branch-fzf' -d 'Interactive fuzzy Git branch switcher with preview of latest commit log'
complete -c cx -n '__fish_use_subcommand' -a 'git-squash' -d 'Interactive commit squasher combining last N commits into one'
complete -c cx -n '__fish_use_subcommand' -a 'git-stash-pop' -d 'Fuzzy browse stashes with diff preview and apply'
complete -c cx -n '__fish_use_subcommand' -a 'git-clean-branches' -d 'Prune local branches already merged into default branch'
complete -c cx -n '__fish_use_subcommand' -a 'docker-fzf' -d 'Multi-select Docker container manager (start, stop, logs, restart)'
complete -c cx -n '__fish_use_subcommand' -a 'docker-prune' -d 'Clean all dangling Docker images, volumes, and networks'
complete -c cx -n '__fish_use_subcommand' -a 'venv-init' -d 'One-key .venv creation, activation, and pip update in cwd'
complete -c cx -n '__fish_use_subcommand' -a 'cheat' -d 'Interactive programming cheatsheet lookup via cht.sh/<lang>/<query>'
complete -c cx -n '__fish_use_subcommand' -a 'hex-view' -d 'Quick terminal hex dump inspection of any binary file'
complete -c cx -n '__fish_use_subcommand' -a 'clip-hist' -d 'Fuzzy search clipboard history and copy selection to active buffer'
complete -c cx -n '__fish_use_subcommand' -a 'qr-gen' -d 'Generate terminal ANSI QR code from any string or file path'
complete -c cx -n '__fish_use_subcommand' -a 'qr-read' -d 'Scan QR code from screen capture or image file'
complete -c cx -n '__fish_use_subcommand' -a 'tar-pack' -d 'Interactive archive creator (tar.gz, tar.zst, zip) with progress'
complete -c cx -n '__fish_use_subcommand' -a 'tar-unpack' -d 'Extract any compressed archive automatically detecting format'
complete -c cx -n '__fish_use_subcommand' -a 'hash-check' -d 'Calculate and compare MD5/SHA256 checksums interactively'
complete -c cx -n '__fish_use_subcommand' -a 'weather' -d 'Minimalist ANSI terminal weather forecast for current location (wttr.in/?0)'
complete -c cx -n '__fish_use_subcommand' -a 'calc' -d 'Fast mathematical evaluator supporting basic arithmetic, roots, and trigonometry'
complete -c cx -n '__fish_use_subcommand' -a 'timer' -d 'Countdown timer with terminal progress bar and desktop audio chime on completion'
complete -c cx -n '__fish_use_subcommand' -a 'stopwatch' -d 'Precision terminal stopwatch with split times'
complete -c cx -n '__fish_use_subcommand' -a 'notes' -d 'Instant markdown scratchpad opened in $EDITOR saved with timestamp to ~/.local/share/corex/notes/'
complete -c cx -n '__fish_use_subcommand' -a 'todo' -d 'Minimalist CLI task tracker with fuzzy completion checklist'
complete -c cx -n '__fish_use_subcommand' -a 'url-short' -d 'Generate a quick shortened URL from clipboard'
complete -c cx -n '__fish_use_subcommand' -a 'trash-empty' -d 'Display size of trash directory and perform safe wipe'
complete -c cx -n '__fish_use_subcommand' -a 'sys-info' -d 'Pristine, customized minimalist hardware/OS summary card without bloated screenfetch ASCII'
complete -c cx -n '__fish_use_subcommand' -a 'irq-top' -d 'Real-time terminal dashboard of hardware & software interrupts per CPU core to track latency spikes'
complete -c cx -n '__fish_use_subcommand' -a 'dmesg-follow' -d 'Colorized, human-readable kernel ring buffer log stream filtering out noise and flagging hardware errors'
complete -c cx -n '__fish_use_subcommand' -a 'kmod-fzf' -d 'Interactive browser of loaded kernel modules (lsmod) showing memory size, dependencies & one-key reload'
complete -c cx -n '__fish_use_subcommand' -a 'sysctl-search' -d 'Fuzzy search across all active Linux kernel runtime parameters (sysctl -a) with live value inspection'
complete -c cx -n '__fish_use_subcommand' -a 'cgroup-inspect' -d 'Visual breakdown of memory, swap, and CPU limits applied to user services and slice groups'
complete -c cx -n '__fish_use_subcommand' -a 'oom-score' -d 'Display processes ranked by Out-Of-Memory killer badness score (oom_score) to identify kill targets'
complete -c cx -n '__fish_use_subcommand' -a 'klog-err' -d 'Scan dmesg specifically for hardware MCE, PCIe AER, and kernel taint warnings'
complete -c cx -n '__fish_use_subcommand' -a 'pcie-topo' -d 'Tree view of PCIe topology, lane speeds (e.g. Gen4 x16), and link degradation'
complete -c cx -n '__fish_use_subcommand' -a 'slab-top' -d 'Real-time slab allocator kernel cache inspection'
complete -c cx -n '__fish_use_subcommand' -a 'numa-stat' -d 'Display NUMA node memory balancing, hit/miss allocations, and CPU affinity'
complete -c cx -n '__fish_use_subcommand' -a 'ipc-audit' -d 'Audit Linux POSIX shared memory segments, message queues, and semaphores'
complete -c cx -n '__fish_use_subcommand' -a 'vk-caps' -d 'Dump and fuzzy-search supported Vulkan extensions, physical device capabilities, and ray tracing'
complete -c cx -n '__fish_use_subcommand' -a 'vk-layers' -d 'View and toggle active Vulkan implicit/explicit validation and capture layers (MangoHud, OBS)'
complete -c cx -n '__fish_use_subcommand' -a 'glmark-quick' -d 'Run an automated headless OpenGL/Vulkan rendering performance benchmark pass and log results'
complete -c cx -n '__fish_use_subcommand' -a 'shader-cache-purge' -d 'Safely clear Nvidia, Mesa, and DXVK shader cache directories to fix stuttering after updates'
complete -c cx -n '__fish_use_subcommand' -a 'display-edid' -d 'Extract, decode, and parse raw display EDID metadata showing exact refresh timings & color profiles'
complete -c cx -n '__fish_use_subcommand' -a 'vrr-status' -d 'Verify active Variable Refresh Rate (G-Sync/FreeSync Adaptive Sync) state on compositor'
complete -c cx -n '__fish_use_subcommand' -a 'nv-enc-stat' -d 'Real-time monitor of NVENC/NVDEC hardware video encoder/decoder utilization'
complete -c cx -n '__fish_use_subcommand' -a 'dri-info' -d 'Direct Rendering Infrastructure driver state, buffer sharing, and Mesa version'
complete -c cx -n '__fish_use_subcommand' -a 'wayland-diag' -d 'Dump Wayland compositor protocols, active surfaces, and output scaling'
complete -c cx -n '__fish_use_subcommand' -a 'mangohud-config' -d 'Interactive preview and live editing of MangoHud HUD overlay configuration'
complete -c cx -n '__fish_use_subcommand' -a 'ram-breakdown' -d 'Detailed breakdown of physical RAM usage showing active, inactive, dirty writeback & slab cache'
complete -c cx -n '__fish_use_subcommand' -a 'hugepages-toggle' -d 'Enable, disable, or resize transparent and static 2MB/1GB HugePages'
complete -c cx -n '__fish_use_subcommand' -a 'zram-stats' -d 'Display ZRAM/Zswap compression ratios, memory algorithms (zstd/lz4), and throughput efficiency'
complete -c cx -n '__fish_use_subcommand' -a 'io-top' -d 'Monitor real-time disk read/write bandwidth consumption broken down by specific process'
complete -c cx -n '__fish_use_subcommand' -a 'inode-check' -d 'Check filesystem inode usage across all mounted volumes to catch zero-byte inode exhaustion'
complete -c cx -n '__fish_use_subcommand' -a 'file-locks' -d 'Inspect active kernel file locks (lslocks) to debug stuck processes holding files open'
complete -c cx -n '__fish_use_subcommand' -a 'btrfs-scrub' -d 'Trigger and monitor background checksum verification scrub on BTRFS subvolumes'
complete -c cx -n '__fish_use_subcommand' -a 'btrfs-dedup' -d 'Analyze filesystem compression ratios and deduplication candidates'
complete -c cx -n '__fish_use_subcommand' -a 'fstrim-all' -d 'Discard unused blocks on all mounted NVMe and SSD storage pools (sudo fstrim -av)'
complete -c cx -n '__fish_use_subcommand' -a 'smart-health' -d 'Read NVMe/SSD S.M.A.R.T. health, percentage used, spare capacity, and wear levels'
complete -c cx -n '__fish_use_subcommand' -a 'swap-compact' -d 'Flush and re-initialize swap memory to defragment fragmented swap pages'
complete -c cx -n '__fish_use_subcommand' -a 'socket-summary' -d 'Instant breakdown of TCP/UDP connection states (ESTABLISHED, TIME-WAIT, CLOSE-WAIT, SYN-SENT)'
complete -c cx -n '__fish_use_subcommand' -a 'dns-leak-test' -d 'Query external leak testing endpoints to verify DNS requests transit through encrypted tunnels'
complete -c cx -n '__fish_use_subcommand' -a 'tcp-dump-quick' -d 'Launch interactive CLI packet capture on primary interface filtered to HTTP/DNS/TLS handshakes'
complete -c cx -n '__fish_use_subcommand' -a 'ssl-inspect' -d 'Pull and parse remote TLS/SSL certificate chains, expiry dates, and cipher suites for any domain'
complete -c cx -n '__fish_use_subcommand' -a 'mtu-bench' -d 'Run automated packet sweep testing to find exact optimal MTU/MSS size without fragmentation'
complete -c cx -n '__fish_use_subcommand' -a 'route-trace' -d 'High-refresh terminal MTR (My Traceroute) combining traceroute and ping diagnostics across hops'
complete -c cx -n '__fish_use_subcommand' -a 'band-top' -d 'Live per-process network bandwidth monitor showing upload/download rates'
complete -c cx -n '__fish_use_subcommand' -a 'conntrack-dump' -d 'Inspect kernel netfilter connection tracking tables and active NAT states'
complete -c cx -n '__fish_use_subcommand' -a 'dns-benchmark' -d 'Benchmark response latencies across Cloudflare, Quad9, Google, and local DNS resolvers'
complete -c cx -n '__fish_use_subcommand' -a 'wifi-radar' -d 'Scan local 2.4GHz / 5GHz / 6GHz Wi-Fi channels, signal strength (dBm), and BSSID congestion'
complete -c cx -n '__fish_use_subcommand' -a 'firewall-status' -d 'Inspect UFW / iptables / nftables active rulesets and dropped packet counters'
complete -c cx -n '__fish_use_subcommand' -a 'sine-gen' -d 'Generate an ad-hoc, bit-perfect sine wave tone at any target frequency straight to PipeWire'
complete -c cx -n '__fish_use_subcommand' -a 'pink-noise' -d 'Output continuous calibrated pink noise for speaker and headphone acoustic room response testing'
complete -c cx -n '__fish_use_subcommand' -a 'spectrogram' -d 'Launch a live, real-time terminal audio spectrum analyzer bound to default monitor source'
complete -c cx -n '__fish_use_subcommand' -a 'xrun-dump' -d 'Parse PipeWire log output specifically for ALSA/JACK buffer underruns with timestamps & process tags'
complete -c cx -n '__fish_use_subcommand' -a 'audio-resample-bench' -d 'Inspect active resampler quality algorithms (Speex, SOXR, libsamplerate) in sound server'
complete -c cx -n '__fish_use_subcommand' -a 'pw-link-fzf' -d 'Interactive matrix for patching PipeWire audio output and input ports on the fly'
complete -c cx -n '__fish_use_subcommand' -a 'latency-test' -d 'Inspect active PipeWire graph latency, quantum buffer sizes, and clock jitter'
complete -c cx -n '__fish_use_subcommand' -a 'sweep-gen' -d 'Generate 20Hz-20kHz logarithmic audio frequency sweep for frequency response testing'
complete -c cx -n '__fish_use_subcommand' -a 'bit-depth-check' -d 'Audit ALSA and PipeWire hardware playback rate, sample format, and DAC bit depth'
complete -c cx -n '__fish_use_subcommand' -a 'compose-up' -d 'Interactive fzf picker scanning directory trees for docker-compose.yml files and spinning them up'
complete -c cx -n '__fish_use_subcommand' -a 'compose-down' -d 'Stop and clean resources for compose stacks across registered project folders'
complete -c cx -n '__fish_use_subcommand' -a 'container-shell' -d 'One-key interactive drop into an active container\'s bash or sh environment'
complete -c cx -n '__fish_use_subcommand' -a 'image-dive' -d 'Analyze Docker image layer sizes and waste extent using dive inside the terminal'
complete -c cx -n '__fish_use_subcommand' -a 'registry-inspect' -d 'Query remote container registries (Docker Hub, GHCR) for image tags and manifest architecture'
complete -c cx -n '__fish_use_subcommand' -a 'container-stats' -d 'Live graphical CPU, memory, network I/O, and block I/O stream for all running containers'
complete -c cx -n '__fish_use_subcommand' -a 'compose-logs' -d 'Interactive log picker across all microservices defined in compose stacks'
complete -c cx -n '__fish_use_subcommand' -a 'podman-pods' -d 'Interactive management of Podman pod groups and Kubernetes YAML pods'
complete -c cx -n '__fish_use_subcommand' -a 'k8s-nodes' -d 'Quick cluster node status, ready state, and resource pressure (kubectl get nodes)'
complete -c cx -n '__fish_use_subcommand' -a 'port-forward' -d 'Interactive SSH remote or local port-forwarding tunnel generator with visual status'
complete -c cx -n '__fish_use_subcommand' -a 'regex-test' -d 'Fast CLI regular expression testing environment with ANSI match highlighting'
complete -c cx -n '__fish_use_subcommand' -a 'json-pretty' -d 'Interactive terminal JSON/YAML stream viewer and query tool via jq'
complete -c cx -n '__fish_use_subcommand' -a 'diff-patch' -d 'Interactively generate a clean unified Git patch from uncommitted working tree changes'
complete -c cx -n '__fish_use_subcommand' -a 'tokei-count' -d 'Instant source code metric breakdown (lines of code, comments, blanks) across languages'
complete -c cx -n '__fish_use_subcommand' -a 'cron-inspect' -d 'View, edit, and validate all system-wide and user-level cron jobs and systemd timers'
complete -c cx -n '__fish_use_subcommand' -a 'git-bisect-start' -d 'Guide and initiate Git binary search (bisect) between good and bad commits'
complete -c cx -n '__fish_use_subcommand' -a 'sqlite-browser' -d 'Interactive CLI SQLite browser and schema inspector for local database files'
complete -c cx -n '__fish_use_subcommand' -a 'http-bench' -d 'Fast HTTP benchmarking pass on any local API endpoint via wrk or hey'
complete -c cx -n '__fish_use_subcommand' -a 'env-diff' -d 'Interactively compare two .env or configuration files showing missing keys'
complete -c cx -n '__fish_use_subcommand' -a 'perf-stat' -d 'Lightweight CPU cycle, instructions-per-cycle (IPC), and cache miss profiling on any command'
complete -c cx -n '__fish_use_subcommand' -a 'entropy-check' -d 'Check available kernel cryptographic entropy bits in /proc/sys/kernel/random/entropy_avail'
complete -c cx -n '__fish_use_subcommand' -a 'gamescope-run' -d 'Launch targeted game or binary wrapped inside a sandboxed Gamescope micro-compositor'
complete -c cx -n '__fish_use_subcommand' -a 'noise-gate' -d 'Toggle real-time AI noise suppression filter for microphone input'
complete -c cx -n '__fish_use_subcommand' -a 'git-rebase-i' -d 'Interactive rebase helper for the last N commits'
complete -c cx -n '__fish_use_subcommand' -a 'semver-bump' -d 'Interactive Semantic Version bumper (patch, minor, major) for project configs'
complete -c cx -n '__fish_use_subcommand' -a 'k8s-pods-fzf' -d 'Interactive fuzzy selector to view logs or exec into Kubernetes cluster pods'
complete -c corex -w cx
